spring:
  application:
    name: pay
  cloud:
    zookeeper:
      connect-string: ${registers.node0.host}:${registers.node0.port}, ${registers.node1.host}:${registers.node1.port}, ${registers.node2.host}:${registers.node2.port}
server:
  port: 10002
