package io.github.greenhandsw.payzk;

import io.github.greenhandsw.split.DataSourceInterceptor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.context.annotation.Import;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@Import(DataSourceInterceptor.class)
@EntityScan("io.github.greenhandsw.core.entity")
@EnableDiscoveryClient
public class PayZkApplication {

	public static void main(String[] args) {
		SpringApplication.run(PayZkApplication.class, args);
	}

}
