package io.github.greenhandsw.binlogreader;

import com.github.shyiko.mysql.binlog.BinaryLogClient;
import com.github.shyiko.mysql.binlog.event.Event;
import com.github.shyiko.mysql.binlog.event.EventData;
import com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.io.IOException;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@Slf4j
public class BinLogReaderApplication {

    public static void main(String[] args) {
        SpringApplication.run(BinLogReaderApplication.class, args);

        BinaryLogClient client = new BinaryLogClient("127.0.0.1", 3306, "payment", "canal", "cloud");
        client.setServerId(1);

        EventDeserializer eventDeserializer = new EventDeserializer();
        eventDeserializer.setCompatibilityMode(
                EventDeserializer.CompatibilityMode.DATE_AND_TIME_AS_LONG,
                EventDeserializer.CompatibilityMode.CHAR_AND_BINARY_AS_BYTE_ARRAY
        );
        client.setEventDeserializer(eventDeserializer);
        client.setHeartbeatInterval(10000);
        client.registerEventListener(event -> {
            EventData data = event.getData();
            log.info(data.toString());
        });
        try {
            client.connect();
            log.info(client.getGtidSet());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
