server:
  port: 16000
register:
  name: register0
  hostname: localhost
  port: 13000
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${register.name}:${register.port}/eureka/