spring:
  application:
    name: gateway
  profiles:
    active: single
  cloud:
    gateway:
      routes:
        - id: ${order.name}
          uri: lb://${order.name}
          predicates:
            - Path=${order.prefix}/**
            - Cookie=username,GreenhandSW
        - id: search
          uri: http://www.baidu.com
          predicates:
            - Path=/search
          filters:
            - RewritePath=/search,/s
    loadbalancer:
      enabled: true
order:
  name: order
  address: localhost
  port: 12000
  ports:
    - 12000
    - 12001
    - 12002
  prefix: /customer/order

registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002
logging:
  level:
    root: debug