spring:
  application:
    name: order
  profiles:
    active: single
  cloud:
    openfeign:
#      circuitbreaker:
#        enabled: true
      client:
        config:
          default:
#            connect-timeout: 2000
#            read-timeout: 2000
            logger-level: basic

pay:
  name: pay
  prefix: pay
order:
  name: order
  prefix: customer/order
registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002
# @LoadBalanced注解允许通过服务名发起请求，从而实现负载均衡
request:
  service:
    url: http://${pay.name}/${pay.prefix}
logging:
  level:
    root: trace # 可以直接指定对某个类下面的所有方法的日志监控级别
    org.apache.tomcat.util.net: fatal
#    io.github.greenhandsw.ordereurekafeign.controller.OrderController: debug
#    org.springframework.cloud.circuitbreaker.resilience4j: debug

resilience4j:
  ratelimiter:
    instances:
      pay:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 3s
        register-health-indicator: true
        subscribe-for-events: true
  circuitbreaker:
    instances:
      pay:
        failure-rate-threshold: 1 #失败请求百分⽐，超过这个⽐例，CircuitBreaker变为OPEN状态
        sliding-window-size: 10 #滑动窗⼝的⼤⼩，配置COUNT_BASED,表示10个请求，配置TIME_BASED表示10秒
        minimum-number-of-calls: 5 #最⼩请求个数，只有在滑动窗⼝内，请求个数达到这个个数，才会触发CircuitBreader对于断路器的判断
        sliding-window-type: COUNT_BASED #滑动窗⼝的类型
        permitted-number-of-calls-in-half-open-state: 3 #当CircuitBreaker处于HALF_OPEN状态的时候，允许通过的请求个数
#        automaticTransitionFromOpenToHalfOpenEnabled: true #设置true，表示⾃动从OPEN变成HALF_OPEN，即使没有请求过来
        wait-duration-in-open-state: 1s #从OPEN到HALF_OPEN状态需要等待的时间
        record-exceptions: #异常名单
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
        event-consumer-buffer-size: 10
        register-health-indicator: true
  timelimiter:
    instances:
      pay:
        timeoutDuration: 2s
        cancelRunningFuture: true
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
