server:
  port: 12000
eureka:
  instance:
    hostname: localhost
    instance-id: order${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${registers.node0.host}:${registers.node0.port}/eureka/, http://${registers.node1.host}:${registers.node1.port}/eureka/, http://${registers.node2.host}:${registers.node2.port}/eureka/
