spring:
  application:
    name: order
  profiles:
    active: single
pay:
  name: pay
  address: localhost
  port: 10000
  ports:
    - 10000
    - 10001
    - 10002
  prefix: pay

registers:
  node0:
    name: center0
    host: localhost
    port: 13000
  node1:
    name: center1
    host: localhost
    port: 13001
  node2:
    name: center2
    host: localhost
    port: 13002
# 暂时写成请求一个固定节点，后面看怎么扩展
request:
  service:
    url: http://${pay.address}:${pay.port}/${pay.prefix}
