spring:
  application:
    name: order
  profiles:
    active: single
pay:
  name: pay
  address: localhost
  port: 10000
  ports:
    - 10000
    - 10001
    - 10002
  prefix: pay

registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002
# @LoadBalanced注解允许通过服务名发起请求，从而实现负载均衡
request:
  service:
    url: http://${pay.name}/${pay.prefix}
