spring:
  application:
    name: order
  profiles:
    active: single
pay:
  name: pay
  address: localhost
  port: 10000
  prefix: pay
registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002
# 暂时写成请求一个固定节点，后面看怎么扩展
request:
  service:
    url: http://${pay.address}:${pay.port}/${pay.prefix}