spring:
  cloud:
    zookeeper:
      connect-string: ${registers.node0.name}:${registers.node0.port}, ${registers.node1.name}:${registers.node1.port}, ${registers.node2.name}:${registers.node2.port}
server:
  port: 12001