spring:
  application:
    name: order
  profiles:
    active: single
pay:
  name: pay
  address: localhost
  port: 10000
  prefix: pay

#  spring.datasource.url=jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=bytedance
#spring.data.jpa.repositories.enabled=true
druid:
  pay:
    master:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3307/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3308/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver

zookeepers:
  zk0:
    name: zk0
    host: localhost
    port: 14000
  zk1:
    name: zk0
    host: localhost
    port: 14001
  zk2:
    name: zk0
    host: localhost
    port: 14002
# 暂时写成请求一个固定节点，后面看怎么扩展
request:
  service:
    url: http://${pay.name}${pay.port}/${pay.prefix}