spring:
  application:
    name: order
  profiles:
    active: single
pay:
  name: pay
  address: localhost
  port: 10000
  prefix: pay
zookeepers:
  zk0:
    name: zk0
    host: localhost
    port: 14000
  zk1:
    name: zk0
    host: localhost
    port: 14001
  zk2:
    name: zk0
    host: localhost
    port: 14002
# 暂时写成请求一个固定节点，后面看怎么扩展
request:
  service:
    url: http://${pay.address}:${pay.port}/${pay.prefix}