spring:
  application:
    name: RegCenter
  profiles:
    active: single
server:
  port: 13000
eureka:
  instance:
    hostname: localhost
centers:
  center0:
    name: center0
    host: localhost
    port: 13000
  center1:
    name: center1
    host: localhost
    port: 13001
  center2:
    name: center2
    host: localhost
    port: 13002