spring:
  application:
    name: RegCenter2
server:
  port: 13002

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${centers.center0.name}:${centers.center0.port}/eureka/, http://${centers.center1.name}:${centers.center1.port}/eureka/
