server:
  port: 13001
eureka:
  instance:
    hostname: ${registers.node1.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${registers.node0.name}:${registers.node0.port}/eureka/, http://${registers.node2.name}:${registers.node2.port}/eureka/
