spring:
  application:
    name: EurekaServer1
server:
  port: 13001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.server0.name}:${eureka.server0.port}/eureka/, http://${eureka.server2.name}:${eureka.server2.port}/eureka/
