spring:
  application:
    name: EurekaServer
  profiles:
    active: single
server:
  port: 13000
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002