server:
  port: 13000
eureka:
  instance:
    hostname: ${registers.node0.name}
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${registers.node1.name}:${registers.node1.port}/eureka/, http://${registers.node2.name}:${registers.node2.port}/eureka/
