version: '2'
services:
  zk0:
    image: zookeeper
    hostname: zk0
    container_name: zk0
    ports:
      - "13000:2181"
    networks:
      cloud:
    volumes:
      - ./zk0/data:/data
      - ./zk0/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: server.0=0.0.0.0:2888:3888;2181 server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181
      TZ: Asia/Shanghai
  zk1:
    image: zookeeper
    hostname: zk1
    container_name: zk1
    ports:
      - "13001:2181"
    networks:
      cloud:
    volumes:
      - ./zk1/data:/data
      - ./zk1/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.0=zk0:2888:3888;2181 server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181
      TZ: Asia/Shanghai
  zk2:
    image: zookeeper
    hostname: zk2
    container_name: zk2
    ports:
      - "13002:2181"
    networks:
      cloud:
    volumes:
      - ./zk2/data:/data
      - ./zk2/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.0=zk0:2888:3888;2181 server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181
      TZ: Asia/Shanghai

networks:
  cloud:
    external: true