version: '2'
services:
  zk0:
    image: zookeeper
    hostname: zk0
    container_name: zk0
    ports:
      - "13000:2181"
    networks:
      cloud:
    volumes:
      - ./zk0/data:/data
      - ./zk0/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: server.0=0.0.0.0:2888:3888;2181 server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181
      TZ: Asia/Shanghai
  zk1:
    image: zookeeper
    hostname: zk1
    container_name: zk1
    ports:
      - "13001:2181"
    networks:
      cloud:
    volumes:
      - ./zk1/data:/data
      - ./zk1/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.0=zk0:2888:3888;2181 server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181
      TZ: Asia/Shanghai
  zk2:
    image: zookeeper
    hostname: zk2
    container_name: zk2
    ports:
      - "13002:2181"
    networks:
      cloud:
    volumes:
      - ./zk2/data:/data
      - ./zk2/datalog:/datalog
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.0=zk0:2888:3888;2181 server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181
      TZ: Asia/Shanghai
#  kafka0:
#    image: bitnami/kafka
#    hostname: kafka0
#    container_name: kafka0
#    networks:
#      cloud:
#    ports:
#      - "13100:9092"
#    environment:
#      KAFKA_BROKER_ID: 0
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:13100
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:13100
#      KAFKA_ZOOKEEPER_CONNECT: "zk0:2181,zk1:2181,zk2:2181"
#      KAFKA_CREATE_TOPICS: "pay"
#    depends_on:
#      - zk0
#      - zk1
#      - zk2
#    volumes:
#      - kafka0:/bitnami/kafka
#  kafka1:
#    image: bitnami/kafka
#    hostname: kafka1
#    container_name: kafka1
#    networks:
#      cloud:
#    ports:
#      - "13101:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:13101
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:13101
#      KAFKA_ZOOKEEPER_CONNECT: "zk0:2181,zk1:2181,zk2:2181"
#      KAFKA_CREATE_TOPICS: "pay"
#    depends_on:
#      - zk0
#      - zk1
#      - zk2
#    volumes:
#      - kafka1:/bitnami/kafka
#  kafka2:
#    image: bitnami/kafka
#    hostname: kafka2
#    container_name: kafka2
#    networks:
#      cloud:
#    ports:
#      - "13102:9092"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:13102
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:13102
#      KAFKA_ZOOKEEPER_CONNECT: "zk0:2181,zk1:2181,zk2:2181"
#      KAFKA_CREATE_TOPICS: "pay"
#    depends_on:
#      - zk0
#      - zk1
#      - zk2
#    volumes:
#      - kafka2:/bitnami/kafka
networks:
  cloud:
    external: true
#volumes:
#  kafka0:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./kafka0
#  kafka1:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./kafka1
#  kafka2:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ./kafka2
