server:
  port: 10000
eureka:
  instance:
    hostname: localhost
    instance-id: pay${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${registers.node0.name}:${registers.node0.port}/eureka/, http://${registers.node1.name}:${registers.node1.port}/eureka/, http://${registers.node2.name}:${registers.node2.port}/eureka/
