spring:
  application:
    name: pay
  profiles:
    active: single
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  data:
    redis:
      host: localhost
      timeout: 10000ms # 连接超时时间（记得添加单位，Duration）
      #      database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片 (默认0)
      #      port: 15000 # Redis服务器连接端口
      cluster:
        nodes: 172.200.0.1:15000,172.200.0.1:15001,172.200.0.1:15002,172.200.0.1:15003,172.200.0.1:15004,172.200.0.1:15005
      password: cloud
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: example
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

druid:
  pay:
    master:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3306/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3307/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      username: root
      password: cloud
      url: jdbc:mysql://localhost:3308/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver

registers:
  node0:
    name: register0
    host: localhost
    port: 13000
  node1:
    name: register1
    host: localhost
    port: 13001
  node2:
    name: register2
    host: localhost
    port: 13002
server:
  tomcat:
    threads:
      min-spare: 5
      max: 5
    max-connections: 10
    accept-count: 10
logging:
  level:
    root: trace
    org.apache.tomcat.util.net: fatal
    com.netflix.discovery.shared.resolver.aws: fatal

video:
  all: video_all_ids
  play:
    count:
      total: video_play_cnt_total
      hot: video_play_cnt_hot