server:
  port: 10000
register:
  name: register0
  hostname: localhost
  port: 13000
eureka:
  instance:
    hostname: localhost
    instance-id: pay${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${register.name}:${register.port}/eureka/